/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pi' at '25/02/18 1:38 PM' with Gradle 3.2.1
 *
 * @author pi, @date 25/02/18 1:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
